@startuml
skinparam actorPosition top
left to right direction

actor "Usuário" as user
actor "Edmar" as Edmar

rectangle "Auxiliar o Edmar na gestão de Empréstimos Escolares e Achados e Perdidos" {
    rectangle "Empréstimo de material" {
        usecase "Solicitação de empréstimo de material"
        usecase "Realizar devolução"
        usecase "Solicitar extensão do período de empréstimo"
        usecase "Solicitar a leva do item para casa"
    }

    rectangle "Achados e perdidos" {

    }
    

}
@enduml