@startuml   

class "Pessoa" as pes{
    -String nome
    -Int id
    -String telefone
    -String email

    +Void cadastroPessoa()
}
 
class "Aluno" as alu{
    -Pessoa pessoa
    -String ra
    -String curso
    -Int serie

    +Boolean validarRA()
}

class "Materiais" as mat{
    -Int id
    -String nome
    -Int quantiaTotal
    -Int quantiaDisponivel

    +cadastro(): void
}

class "Emprestimo" as emp{
    -Int id
    -Materiais material
    -Pessoa pessoa
    -datetime horaDaRetirada
    -datetime horaDaDevolucao

    +Void cadastroEmprestimo()
    +Boolean verificacaoDeDisponibilidade()
    +devolucao(): void
    +gerarDocumentoAssinatura(): 
}

class Perdido {
    -dataCadastro: Date
    -prazoNormativo: Date
    -status: String
    +excederItem(): void
    +solicitarRecuperacao(): void
}

class Relatorio {
    -dataInicial: Date
    -dataFinal: Date
}

class Item {
    -descricaoItem: String  
}

pes o-- alu
Emprestimo o-- Materiais
Perdido o-- Item

@enduml
